/*
 * Copyright (c) 2019. terefang@gmail.com
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.github.terefang.jmelange.pdf.core.values;

public class PdfName extends AbstractPdfValue
{
	private String name;
	
	public static PdfName of(String name)
	{
		return new PdfName(name);
	}
	
	public static PdfName create()
	{
		return new PdfName();
	}
	
	public PdfName()
	{
	}
	
	public PdfName(String name)
	{
		this.name = name;
	}
	
	public String getName()
	{
		return name;
	}
	
	public void setName(String name)
	{
		this.name = name;
	}
	
	public String asString()
	{
		StringBuilder _sb = new StringBuilder();
		_sb.append("/");
		for(char _c : name.toCharArray())
		{
			if(_c=='#')
			{
				_sb.append("#23");
			}
			else
			if(_c>='!' && _c<='~')
			{
				_sb.append(_c);
			}
			else
			if(_c>0xff)
			{
				_sb.append("#20");
			}
			else
			{
				_sb.append(String.format("#%02X", (int)_c));
			}
		}
		return _sb.toString();
	}

	public static final String _3D = "3D";
	public static final String A = "A";
	public static final String AA = "AA";
	public static final String ABSOLUTECOLORIMETRIC = "AbsoluteColorimetric";
	public static final String AC = "AC";
	public static final String ACROFORM = "AcroForm";
	public static final String ACTION = "Action";
	public static final String ACTIVATION = "Activation";
	public static final String ADBE = "ADBE";
	public static final String ACTUALTEXT = "ActualText";
	public static final String ADBE_PKCS7_DETACHED = "adbe.pkcs7.detached";
	public static final PdfName ADBE_PKCS7_S4 =new PdfName("adbe.pkcs7.s4");
	public static final PdfName ADBE_PKCS7_S5 =new PdfName("adbe.pkcs7.s5");
	public static final String ADBE_PKCS7_SHA1 = "adbe.pkcs7.sha1";
	public static final String ADBE_X509_RSA_SHA1 = "adbe.x509.rsa_sha1";
	public static final String ADOBE_PPKLITE = "Adobe.PPKLite";
	public static final String ADOBE_PPKMS = "Adobe.PPKMS";
	public static final String AESV2 = "AESV2";
	public static final String AIS = "AIS";
	public static final String ALLPAGES = "AllPages";
	public static final String ALT = "Alt";
	public static final String ALTERNATE = "Alternate";
	public static final String ANIMATION = "Animation";
	public static final String ANNOT = "Annot";
	public static final String ANNOTS = "Annots";
	public static final String ANTIALIAS = "AntiAlias";
	public static final String AP = "AP";
	public static final String APPDEFAULT = "AppDefault";
	public static final String ART = "Art";
	public static final String ARTBOX = "ArtBox";
	public static final String ASCENT = "Ascent";
	public static final String AS = "AS";
	public static final String ASCII85DECODE = "ASCII85Decode";
	public static final String ASCIIHEXDECODE = "ASCIIHexDecode";
	public static final String ASSET = "Asset";
	public static final String ASSETS = "Assets";
	public static final String AUTHEVENT = "AuthEvent";
	public static final String AUTHOR = "Author";
	public static final String B = "B";
	public static final String BACKGROUND = "Background";
	public static final String BASEENCODING = "BaseEncoding";
	public static final String BASEFONT = "BaseFont";
	public static final String BASEVERSION = "BaseVersion";
	public static final String BBOX = "BBox";
	public static final String BC = "BC";
	public static final String BG = "BG";
	public static final String BIBENTRY = "BibEntry";
	public static final String BIGFIVE = "BigFive";
	public static final String BINDING = "Binding";
	public static final String BINDINGMATERIALNAME = "BindingMaterialName";
	public static final String BITSPERCOMPONENT = "BitsPerComponent";
	public static final String BITSPERSAMPLE = "BitsPerSample";
	public static final String BL = "Bl";
	public static final String BLACKIS1 = "BlackIs1";
	public static final String BLACKPOINT = "BlackPoint";
	public static final String BLOCKQUOTE = "BlockQuote";
	public static final String BLEEDBOX = "BleedBox";
	public static final String BLINDS = "Blinds";
	public static final String BM = "BM";
	public static final String BORDER = "Border";
	public static final String BOUNDS = "Bounds";
	public static final String BOX = "Box";
	public static final String BS = "BS";
	public static final String BTN = "Btn";
	public static final String BYTERANGE = "ByteRange";
	public static final String C = "C";
	public static final String C0 = "C0";
	public static final String C1 = "C1";
	public static final String CA = "CA";
	public static final String ca = "ca";
	public static final String CALGRAY = "CalGray";
	public static final String CALRGB = "CalRGB";
	public static final String CAPHEIGHT = "CapHeight";
	public static final String CAPTION = "Caption";
	public static final String CATALOG = "Catalog";
	public static final String CATEGORY = "Category";
	public static final String CCITTFAXDECODE = "CCITTFaxDecode";
	public static final String CENTER = "Center";
	public static final String CENTERWINDOW = "CenterWindow";
	public static final String CERT = "Cert";
	public static final String CF = "CF";
	public static final String CFM = "CFM";
	public static final String CH = "Ch";
	public static final String CHARPROCS = "CharProcs";
	public static final String CI = "CI";
	public static final String CIDFONTTYPE0 = "CIDFontType0";
	public static final String CIDFONTTYPE2 = "CIDFontType2";
	public static final String CIDSET = "CIDSet";
	public static final String CIDSYSTEMINFO = "CIDSystemInfo";
	public static final String CIDTOGIDMAP = "CIDToGIDMap";
	public static final String CIRCLE = "Circle";
	public static final String CMD = "CMD";
	public static final String CO = "CO";
	public static final String CODE = "Code";
	public static final String COLORS = "ColorDef";
	public static final String COLORSPACE = "ColorSpace";
	public static final String COLLECTION = "Collection";
	public static final String COLLECTIONFIELD = "CollectionField";
	public static final String COLLECTIONITEM = "CollectionItem";
	public static final String COLLECTIONSCHEMA = "CollectionSchema";
	public static final String COLLECTIONSORT = "CollectionSort";
	public static final String COLLECTIONSUBITEM = "CollectionSubitem";
	public static final String COLUMNS = "Columns";
	public static final String CONDITION = "Condition";
	public static final String CONFIGURATION = "Configuration";
	public static final String CONFIGURATIONS = "Configurations";
	public static final String CONTACTINFO = "ContactInfo";
	public static final String CONTENT = "Content";
	public static final String CONTENTS = "Contents";
	public static final String COORDS = "Coords";
	public static final String COUNT = "Count";
	public static final String COURIER = "Courier";
	public static final String COURIER_BOLD = "Courier-Bold";
	public static final String COURIER_OBLIQUE = "Courier-Oblique";
	public static final String COURIER_BOLDOBLIQUE = "Courier-BoldOblique";
	public static final String CREATIONDATE = "CreationDate";
	public static final String CREATOR = "Creator";
	public static final String CREATORINFO = "CreatorInfo";
	public static final String CROPBOX = "CropBox";
	public static final String CRYPT = "Crypt";
	public static final String CS = "CS";
	public static final String CUEPOINT = "CuePoint";
	public static final String CUEPOINTS = "CuePoints";
	public static final String D = "D";
	public static final String DA = "DA";
	public static final String DATA = "Data";
	public static final String DC = "DC";
	public static final String DCTDECODE = "DCTDecode";
	public static final String DEACTIVATION = "Deactivation";
	public static final String DECODE = "Decode";
	public static final String DECODEPARMS = "DecodeParms";
	public static final String DEFAULT = "Default";
	public static final String DEFAULTCRYPTFILTER = "DefaultCryptFilter";
	public static final String DEFAULTCMYK = "DefaultCMYK";
	public static final String DEFAULTGRAY = "DefaultGray";
	public static final String DEFAULTRGB = "DefaultRGB";
	public static final String DESC = "Desc";
	public static final String DESCENDANTFONTS = "DescendantFonts";
	public static final String DESCENT = "Descent";
	public static final String DEST = "Dest";
	public static final String DESTOUTPUTPROFILE = "DestOutputProfile";
	public static final String DESTS = "Dests";
	public static final String DEVICEGRAY = "DeviceGray";
	public static final String DEVICERGB = "DeviceRGB";
	public static final String DEVICECMYK = "DeviceCMYK";
	public static final String DI = "Di";
	public static final String DIFFERENCES = "Differences";
	public static final String DISSOLVE = "Dissolve";
	public static final String DIRECTION = "Direction";
	public static final String DISPLAYDOCTITLE = "DisplayDocTitle";
	public static final String DIV = "Div";
	public static final String DM = "Dm";
	public static final String DOCMDP = "DocMDP";
	public static final String DOCOPEN = "DocOpen";
	public static final PdfName DOCUMENT = new PdfName( "Document" );
	public static final String DOMAIN = "Domain";
	public static final String DP = "DP";
	public static final String DR = "DR";
	public static final String DS = "DS";
	public static final String DUR = "Dur";
	public static final String DUPLEX = "Duplex";
	public static final String DUPLEXFLIPSHORTEDGE = "DuplexFlipShortEdge";
	public static final String DUPLEXFLIPLONGEDGE = "DuplexFlipLongEdge";
	public static final String DV = "DV";
	public static final String DW = "DW";
	public static final String E = "E";
	public static final String EARLYCHANGE = "EarlyChange";
	public static final String EF = "EF";
	public static final String EFF = "EFF";
	public static final String EFOPEN = "EFOpen";
	public static final String EMBEDDED = "Embedded";
	public static final String EMBEDDEDFILE = "EmbeddedFile";
	public static final String EMBEDDEDFILES = "EmbeddedFiles";
	public static final String ENCODE = "Encode";
	public static final String ENCODEDBYTEALIGN = "EncodedByteAlign";
	public static final String ENCODING = "Encoding";
	public static final String ENCRYPT = "Encrypt";
	public static final String ENCRYPTMETADATA = "EncryptMetadata";
	public static final String ENDOFBLOCK = "EndOfBlock";
	public static final String ENDOFLINE = "EndOfLine";
	public static final String EXTEND = "Extend";
	public static final String EXTENSIONS = "Extensions";
	public static final String EXTENSIONLEVEL = "ExtensionLevel";
	public static final String EXTGSTATE = "ExtGState";
	public static final String EXPORT = "Export";
	public static final String EXPORTSTATE = "ExportState";
	public static final String EVENT = "Event";
	public static final String F = "F";
	public static final String FAR = "Far";
	public static final String FB = "FB";
	public static final String FDECODEPARMS = "FDecodeParms";
	public static final String FDF = "FDF";
	public static final String FF = "Ff";
	public static final String FFILTER = "FFilter";
	public static final String FIELDS = "Fields";
	public static final PdfName FIGURE = new PdfName( "Figure" );
	public static final String FILEATTACHMENT = "FileAttachment";
	public static final String FILESPEC = "Filespec";
	public static final String FILTER = "Filter";
	public static final String FIRST = "First";
	public static final String FIRSTCHAR = "FirstChar";
	public static final String FIRSTPAGE = "FirstPage";
	public static final String FIT = "Fit";
	public static final String FITH = "FitH";
	public static final String FITV = "FitV";
	public static final String FITR = "FitR";
	public static final String FITB = "FitB";
	public static final String FITBH = "FitBH";
	public static final String FITBV = "FitBV";
	public static final String FITWINDOW = "FitWindow";
	public static final String FLAGS = "Flags";
	public static final String FLASH = "Flash";
	public static final String FLASHVARS = "FlashVars";
	public static final String FLATEDECODE = "FlateDecode";
	public static final String FO = "Fo";
	public static final String FONT = "Font";
	public static final String FONTBBOX = "FontBBox";
	public static final String FONTDESCRIPTOR = "FontDescriptor";
	public static final String FONTFILE = "FontFile";
	public static final String FONTFILE2 = "FontFile2";
	public static final String FONTFILE3 = "FontFile3";
	public static final String FONTMATRIX = "FontMatrix";
	public static final String FONTNAME = "FontName";
	public static final String FOREGROUND = "Foreground";
	public static final String FORM = "Form";
	public static final String FORMTYPE = "FormType";
	public static final PdfName FORMULA = new PdfName( "Formula" );
	public static final String FREETEXT = "FreeText";
	public static final String FRM = "FRM";
	public static final String FS = "FS";
	public static final String FT = "FT";
	public static final String FULLSCREEN = "FullScreen";
	public static final String FUNCTION = "Function";
	public static final String FUNCTIONS = "Functions";
	public static final String FUNCTIONTYPE = "FunctionType";
	public static final String GAMMA = "Gamma";
	public static final String GBK = "GBK";
	public static final String GLITTER = "Glitter";
	public static final String GOTO = "GoTo";
	public static final String GOTOE = "GoToE";
	public static final String GOTOR = "GoToR";
	public static final String GROUP = "Group";
	public static final String GTS_PDFA1 = "GTS_PDFA1";
	public static final String GTS_PDFX = "GTS_PDFX";
	public static final String GTS_PDFXVERSION = "GTS_PDFXVersion";
	public static final String H = "H";
	public static final PdfName H1 = new PdfName( "H1" );
	public static final String H2 = "H2";
	public static final String H3 = "H3";
	public static final String H4 = "H4";
	public static final String H5 = "H5";
	public static final String H6 = "H6";
	public static final String HALIGN = "HAlign";
	public static final String HEIGHT = "Height";
	public static final String HELV = "Helv";
	public static final String HELVETICA = "Helvetica";
	public static final String HELVETICA_BOLD = "Helvetica-Bold";
	public static final String HELVETICA_OBLIQUE = "Helvetica-Oblique";
	public static final String HELVETICA_BOLDOBLIQUE = "Helvetica-BoldOblique";
	public static final String HID = "Hid";
	public static final String HIDE = "Hide";
	public static final String HIDEMENUBAR = "HideMenubar";
	public static final String HIDETOOLBAR = "HideToolbar";
	public static final String HIDEWINDOWUI = "HideWindowUI";
	public static final String HIGHLIGHT = "Highlight";
	public static final String HOFFSET = "HOffset";
	public static final String I = "I";
	public static final String ICCBASED = "ICCBased";
	public static final String ID = "ID";
	public static final String IDENTITY = "Identity";
	public static final String IF = "IF";
	public static final String IMAGE = "Image";
	public static final String IMAGEB = "ImageB";
	public static final String IMAGEC = "ImageC";
	public static final String IMAGEI = "ImageI";
	public static final String IMAGEMASK = "ImageMask";
	public static final String INDEX = "Index";
	public static final String INDEXED = "Indexed";
	public static final String INFO = "Info";
	public static final String INK = "Ink";
	public static final String INKLIST = "InkList";
	public static final String INSTANCES = "Instances";
	public static final String IMPORTDATA = "ImportData";
	public static final String INTENT = "Intent";
	public static final String INTERPOLATE = "Interpolate";
	public static final String ISMAP = "IsMap";
	public static final String IRT = "IRT";
	public static final String ITALICANGLE = "ItalicAngle";
	public static final String ITXT = "ITXT";
	public static final String IX = "IX";
	public static final String JAVASCRIPT = "JavaScript";
	public static final String JBIG2DECODE = "JBIG2Decode";
	public static final String JBIG2GLOBALS = "JBIG2Globals";
	public static final String JPXDECODE = "JPXDecode";
	public static final String JS = "JS";
	public static final String K = "K";
	public static final String KEYWORDS = "Keywords";
	public static final String KIDS = "Kids";
	public static final String L = "L";
	public static final String L2R = "L2R";
	public static final String LANG = "Lang";
	public static final String LANGUAGE = "Language";
	public static final String LAST = "Last";
	public static final String LASTCHAR = "LastChar";
	public static final String LASTPAGE = "LastPage";
	public static final String LAUNCH = "Launch";
	public static final String LBL = "Lbl";
	public static final String LBODY = "LBody";
	public static final String LENGTH = "Length";
	public static final String LENGTH1 = "Length1";
	public static final String LI = "LI";
	public static final String LIMITS = "Limits";
	public static final String LINE = "Line";
	public static final String LINEAR = "Linear";
	public static final String LINK = "Link";
	public static final String LISTMODE = "ListMode";
	public static final String LOCATION = "Location";
	public static final String LOCK = "Lock";
	public static final String LOCKED = "Locked";
	public static final String LZWDECODE = "LZWDecode";
	public static final String M = "M";
	public static final String MATERIAL = "Material";
	public static final String MATRIX = "Matrix";
	public static final String MAC_EXPERT_ENCODING = "MacExpertEncoding";
	public static final String MAC_ROMAN_ENCODING = "MacRomanEncoding";
	public static final String MARKED = "Marked";
	public static final String MARKINFO = "MarkInfo";
	public static final String MASK = "Mask";
	public static final String MAX_LOWER_CASE = "max";
	public static final String MAX_CAMEL_CASE = "Max";
	public static final String MAXLEN = "MaxLen";
	public static final String MEDIABOX = "MediaBox";
	public static final String MCID = "MCID";
	public static final String MCR = "MCR";
	public static final String METADATA = "Metadata";
	public static final String MIN_LOWER_CASE = "min";
	public static final String MIN_CAMEL_CASE = "Min";
	public static final String MK = "MK";
	public static final String MMTYPE1 = "MMType1";
	public static final String MODDATE = "ModDate";
	public static final String N = "N";
	public static final String N0 = "n0";
	public static final String N1 = "n1";
	public static final String N2 = "n2";
	public static final String N3 = "n3";
	public static final String N4 = "n4";
	public static final String NAME = "Name";
	public static final String NAMED = "Named";
	public static final String NAMES = "Names";
	public static final String NAVIGATION = "Navigation";
	public static final String NAVIGATIONPANE = "NavigationPane";
	public static final String NEAR = "Near";
	public static final String NEEDAPPEARANCES = "NeedAppearances";
	public static final String NEWWINDOW = "NewWindow";
	public static final String NEXT = "Next";
	public static final String NEXTPAGE = "NextPage";
	public static final String NM = "NM";
	public static final String NONE = "None";
	public static final String NONFULLSCREENPAGEMODE = "NonFullScreenPageMode";
	public static final String NONSTRUCT = "NonStruct";
	public static final String NOTE = "Note";
	public static final String NUMCOPIES = "NumCopies";
	public static final String NUMS = "Nums";
	public static final String O = "O";
	public static final String OBJ = "Obj";
	public static final String OBJR = "OBJR";
	public static final String OBJSTM = "ObjStm";
	public static final String OC = "OC";
	public static final String OCG = "OCG";
	public static final String OCGS = "OCGs";
	public static final String OCMD = "OCMD";
	public static final String OCPROPERTIES = "OCProperties";
	public static final String Off = "Off";
	public static final String OFF = "OFF";
	public static final String ON = "ON";
	public static final String ONECOLUMN = "OneColumn";
	public static final String OPEN = "Open";
	public static final String OPENACTION = "OpenAction";
	public static final String OP = "OP";
	public static final String op = "op";
	public static final String OPM = "OPM";
	public static final String OPT = "Opt";
	public static final String ORDER = "Order";
	public static final String ORDERING = "Ordering";
	public static final String OSCILLATING = "Oscillating";
	public static final String OUTLINES = "Outlines";
	public static final String OUTPUTCONDITION = "OutputCondition";
	public static final String OUTPUTCONDITIONIDENTIFIER = "OutputConditionIdentifier";
	public static final String OUTPUTINTENT = "OutputIntent";
	public static final String OUTPUTINTENTS = "OutputIntents";
	public static final String P = "P";
	public static final String PAGE = "Page";
	public static final String PAGELABELS = "PageLabels";
	public static final String PAGELAYOUT = "PageLayout";
	public static final String PAGEMODE = "PageMode";
	public static final String PAGES = "Pages";
	public static final String PAINTTYPE = "PaintType";
	public static final String PANOSE = "Panose";
	public static final String PARAMS = "Params";
	public static final String PARENT = "Parent";
	public static final String PARENTTREE = "ParentTree";
	public static final PdfName PARENTTREENEXTKEY = new PdfName( "ParentTreeNextKey" );
	public static final PdfName PART = new PdfName( "Part" );
	public static final String PASSCONTEXTCLICK = "PassContextClick";
	public static final String PATTERN = "Pattern";
	public static final String PATTERNTYPE = "PatternType";
	public static final String PC = "PC";
	public static final String PDF = "PDF";
	public static final String PDFDOCENCODING = "PDFDocEncoding";
	public static final String PERCEPTUAL = "Perceptual";
	public static final String PERMS = "Perms";
	public static final String PG = "Pg";
	public static final String PI = "PI";
	public static final String PICKTRAYBYPDFSIZE = "PickTrayByPDFSize";
	public static final String PLAYCOUNT = "PlayCount";
	public static final String PO = "PO";
	public static final String POPUP = "Popup";
	public static final String POSITION = "Position";
	public static final String PREDICTOR = "Predictor";
	public static final String PREFERRED = "Preferred";
	public static final String PRESENTATION = "Presentation";
	public static final String PRESERVERB = "PreserveRB";
	public static final String PREV = "Prev";
	public static final String PREVPAGE = "PrevPage";
	public static final String PRINT = "Print";
	public static final String PRINTAREA = "PrintArea";
	public static final String PRINTCLIP = "PrintClip";
	public static final String PRINTPAGERANGE = "PrintPageRange";
	public static final String PRINTSCALING = "PrintScaling";
	public static final String PRINTSTATE = "PrintState";
	public static final String PRIVATE = "Private";
	public static final String PROCSET = "ProcSet";
	public static final String PRODUCER = "Producer";
	public static final String PROPERTIES = "Properties";
	public static final String PS = "PS";
	public static final String PUBSEC = "Adobe.PubSec";
	public static final String PV = "PV";
	public static final String Q = "Q";
	public static final String QUADPOINTS = "QuadPoints";
	public static final String QUOTE = "Quote";
	public static final String R = "R";
	public static final String R2L = "R2L";
	public static final String RANGE = "Range";
	public static final String RC = "RC";
	public static final String RBGROUPS = "RBGroups";
	public static final String REASON = "Reason";
	public static final String RECIPIENTS = "Recipients";
	public static final String RECT = "Rect";
	public static final String REFERENCE = "Reference";
	public static final String REGISTRY = "Registry";
	public static final String REGISTRYNAME = "RegistryName";
	public static final String RELATIVECOLORIMETRIC = "RelativeColorimetric";
	public static final String RENDITION = "Rendition";
	public static final String RESETFORM = "ResetForm";
	public static final String RESOURCES = "Resources";
	public static final String RI = "RI";
	public static final String RICHMEDIA = "RichMedia";
	public static final String RICHMEDIAACTIVATION = "RichMediaActivation";
	public static final String RICHMEDIAANIMATION = "RichMediaAnimation";
	public static final String RICHMEDIACOMMAND = "RichMediaCommand";
	public static final String RICHMEDIACONFIGURATION = "RichMediaConfiguration";
	public static final String RICHMEDIACONTENT = "RichMediaContent";
	public static final String RICHMEDIADEACTIVATION = "RichMediaDeactivation";
	public static final String RICHMEDIAEXECUTE = "RichMediaExecute";
	public static final String RICHMEDIAINSTANCE = "RichMediaInstance";
	public static final String RICHMEDIAPARAMS = "RichMediaParams";
	public static final String RICHMEDIAPOSITION = "RichMediaPosition";
	public static final String RICHMEDIAPRESENTATION = "RichMediaPresentation";
	public static final String RICHMEDIASETTINGS = "RichMediaSettings";
	public static final String RICHMEDIAWINDOW = "RichMediaWindow";
	public static final String ROLEMAP = "RoleMap";
	public static final String ROOT = "Root";
	public static final String ROTATE = "Rotate";
	public static final String ROWS = "Rows";
	public static final PdfName RUBY = new PdfName( "Ruby" );
	public static final String RUNLENGTHDECODE = "RunLengthDecode";
	public static final String RV = "RV";
	public static final String S = "S";
	public static final String SATURATION = "Saturation";
	public static final String SCHEMA = "Schema";
	public static final String SCREEN = "Screen";
	public static final String SCRIPTS = "Scripts";
	public static final String SECT = "Sect";
	public static final String SEPARATION = "Separation";
	public static final String SETOCGSTATE = "SetOCGState";
	public static final String SETTINGS = "Settings";
	public static final String SHADING = "Shading";
	public static final String SHADINGTYPE = "ShadingType";
	public static final String SHIFT_JIS = "Shift-JIS";
	public static final String SIG = "Sig";
	public static final String SIGFLAGS = "SigFlags";
	public static final String SIGREF = "SigRef";
	public static final String SIMPLEX = "Simplex";
	public static final String SINGLEPAGE = "SinglePage";
	public static final String SIZE = "Size";
	public static final String SMASK = "SMask";
	public static final String SORT = "Sort";
	public static final String SOUND = "Sound";
	public static final String SPAN = "Span";
	public static final String SPEED = "Speed";
	public static final String SPLIT = "Split";
	public static final String SQUARE = "Square";
	public static final String SQUIGGLY = "Squiggly";
	public static final String ST = "St";
	public static final String STAMP = "Stamp";
	public static final String STANDARD = "Standard";
	public static final String STATE = "State";
	public static final String STDCF = "StdCF";
	public static final String STEMV = "StemV";
	public static final String STMF = "StmF";
	public static final String STRF = "StrF";
	public static final String STRIKEOUT = "StrikeOut";
	public static final String STRUCTPARENT = "StructParent";
	public static final String STRUCTPARENTS = "StructParents";
	public static final String STRUCTTREEROOT = "StructTreeRoot";
	public static final String STYLE = "Style";
	public static final String SUBFILTER = "SubFilter";
	public static final String SUBJECT = "Subject";
	public static final String SUBMITFORM = "SubmitForm";
	public static final String SUBTYPE = "Subtype";
	public static final String SUPPLEMENT = "Supplement";
	public static final String SV = "SV";
	public static final String SW = "SW";
	public static final String SYMBOL = "Symbol";
	public static final String T = "T";
	public static final String TA = "TA";
	public static final String TABLE = "Table";
	public static final String TABS = "Tabs";
	public static final String TBODY = "TBody";
	public static final String TD = "TD";
	public static final String TEXT = "Text";
	public static final String TFOOT = "TFoot";
	public static final String TH = "TH";
	public static final String THEAD = "THead";
	public static final String THUMB = "Thumb";
	public static final String THREADS = "Threads";
	public static final String TI = "TI";
	public static final String TIME = "Time";
	public static final String TILINGTYPE = "TilingType";
	public static final String TIMES_ROMAN = "Times-Roman";
	public static final String TIMES_BOLD = "Times-Bold";
	public static final String TIMES_ITALIC = "Times-Italic";
	public static final String TIMES_BOLDITALIC = "Times-BoldItalic";
	public static final String TITLE = "Title";
	public static final String TK = "TK";
	public static final String TM = "TM";
	public static final String TOC = "TOC";
	public static final String TOCI = "TOCI";
	public static final String TOGGLE = "Toggle";
	public static final String TOOLBAR = "Toolbar";
	public static final String TOUNICODE = "ToUnicode";
	public static final String TP = "TP";
	public static final PdfName TABLEROW = new PdfName( "TR" );
	public static final String TRANS = "Trans";
	public static final String TRANSFORMPARAMS = "TransformParams";
	public static final String TRANSFORMMETHOD = "TransformMethod";
	public static final String TRANSPARENCY = "Transparency";
	public static final String TRANSPARENT = "Transparent";
	public static final String TRAPPED = "Trapped";
	public static final String TRIMBOX = "TrimBox";
	public static final String TRUETYPE = "TrueType";
	public static final String TU = "TU";
	public static final String TWOCOLUMNLEFT = "TwoColumnLeft";
	public static final String TWOCOLUMNRIGHT = "TwoColumnRight";
	public static final String TWOPAGELEFT = "TwoPageLeft";
	public static final String TWOPAGERIGHT = "TwoPageRight";
	public static final String TX = "Tx";
	public static final String TYPE = "Type";
	public static final String TYPE0 = "Type0";
	public static final String TYPE1 = "Type1";
	public static final String TYPE3 = "Type3";
	public static final String U = "U";
	public static final String UF = "UF";
	public static final String UHC = "UHC";
	public static final String UNDERLINE = "Underline";
	public static final String UR = "UR";
	public static final String UR3 = "UR3";
	public static final String URI = "URI";
	public static final String URL = "URL";
	public static final String USAGE = "Usage";
	public static final String USEATTACHMENTS = "UseAttachments";
	public static final String USENONE = "UseNone";
	public static final String USEOC = "UseOC";
	public static final String USEOUTLINES = "UseOutlines";
	public static final String USER = "User";
	public static final String USERPROPERTIES = "UserProperties";
	public static final String USERUNIT = "UserUnit";
	public static final String USETHUMBS = "UseThumbs";
	public static final String V = "V";
	public static final String V2 = "V2";
	public static final String VALIGN = "VAlign";
	public static final String VERISIGN_PPKVS = "VeriSign.PPKVS";
	public static final String VERSION = "Version";
	public static final String VIDEO = "Video";
	public static final String VIEW = "View";
	public static final String VIEWS = "Views";
	public static final String VIEWAREA = "ViewArea";
	public static final String VIEWCLIP = "ViewClip";
	public static final String VIEWERPREFERENCES = "ViewerPreferences";
	public static final String VIEWSTATE = "ViewState";
	public static final String VISIBLEPAGES = "VisiblePages";
	public static final String VOFFSET = "VOffset";
	public static final String W = "W";
	public static final String W2 = "W2";
	public static final String WARICHU = "Warichu";
	public static final String WC = "WC";
	public static final String WIDGET = "Widget";
	public static final String WIDTH = "Width";
	public static final String WIDTHS = "Widths";
	public static final String WIN = "Win";
	public static final String WIN_ANSI_ENCODING = "WinAnsiEncoding";
	public static final String WINDOW = "Window";
	public static final String WINDOWED = "Windowed";
	public static final String WIPE = "Wipe";
	public static final String WHITEPOINT = "WhitePoint";
	public static final String WP = "WP";
	public static final String WS = "WS";
	public static final String X = "X";
	public static final String XA = "XA";
	public static final String XD = "XD";
	public static final String XFA = "XFA";
	public static final String XML = "XML";
	public static final String XOBJECT = "XObject";
	public static final String XSTEP = "XStep";
	public static final String XREF = "XRef";
	public static final String XREFSTM = "XRefStm";
	public static final String XYZ = "XYZ";
	public static final String YSTEP = "YStep";
	public static final String ZADB = "ZaDb";
	public static final String ZAPFDINGBATS = "ZapfDingbats";
	public static final String ZOOM = "Zoom";
}
